INSERT INTO `centre`(`ID_CENTRE`, `NOM`, `ADRESSE`, `LAT`, `LNG`) VALUES (1, 'Carbay Rental Montreal Twon Center', '1440 Rue Drummond, Montréal, QC H3B 2E3', '45.49906776844369', '-73.57574883846779');
INSERT INTO `centre`(`ID_CENTRE`, `NOM`, `ADRESSE`, `LAT`, `LNG`) VALUES (2, 'Carbay Rental Montreal AirPort', '5350 Rue Ferrier, Montréal, QC H4P 1L9', '45.496261619460014', '-73.65891653947715');
INSERT INTO `centre`(`ID_CENTRE`, `NOM`, `ADRESSE`, `LAT`, `LNG`) VALUES (3, 'Carbay Rental Trois-Rivières', '727 Rue Saint Christophe, Trois-Rivières, QC G9A 3L9', '46.35723921809508', '-72.55038135103182');
INSERT INTO `centre`(`ID_CENTRE`, `NOM`, `ADRESSE`, `LAT`, `LNG`) VALUES (4, 'Carbay Rental Quebec', '768 Rue Aiguillon, Québec, QC G1R 1M7', '46.81191807217775', '-71.21700334837165');

INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('935 VGA','Jaguar I-Pace','#063970','libre','images_bd/jaguar_i-pace.jpg','Autonomie : 470 kilomètres, 50 CAD/jour', 50, 1);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('VB2 GHF','Jaguar I-Pace','#a6a6a6','libre','images_bd/jaguar_i-pace.jpg','Autonomie : 470 kilomètres, 50 CAD/jour', 50, 2);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('VGH BR4','Jaguar I-Pace','#063970','libre','images_bd/jaguar_i-pace.jpg','Autonomie : 470 kilomètres, 50 CAD/jour', 50, 2);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('BF4 BF5','Jaguar I-Pace','#a6a6a6','enLocation','images_bd/jaguar_i-pace.jpg','Autonomie : 470 kilomètres, 50 CAD/jour', 50, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('VG5 IPB','Jaguar I-Pace','#e64d00','enLocation','images_bd/jaguar_i-pace.jpg','Autonomie : 470 kilomètres, 50 CAD/jour', 50, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('LGB T7R','Jaguar I-Pace','#063970','enLocation','images_bd/jaguar_i-pace.jpg','Autonomie : 470 kilomètres, 50 CAD/jour', 50, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('TRI Q5G','Jaguar I-Pace','#990000','enLocation','images_bd/jaguar_i-pace.jpg','Autonomie : 470 kilomètres, 50 CAD/jour', 50, null);

INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('GH4 FT5','Audi e-tron','#063970','enLocation','images_bd/audi_e-tron.jpg','Autonomie : 436 kilomètres, 45 CAD/jour', 45, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('BR3 TK2','Audi e-tron','#eeeee4','enLocation','images_bd/audi_e-tron.jpg','Autonomie : 436 kilomètres, 45 CAD/jour', 45, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('QR4 FTG','Audi e-tron','#990000','enLocation','images_bd/audi_e-tron.jpg','Autonomie : 436 kilomètres, 45 CAD/jour', 45, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('TGB BG2','Audi e-tron','#a6a6a6','libre','images_bd/audi_e-tron.jpg','Autonomie : 436 kilomètres, 45 CAD/jour', 45, 1);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('BR4 TQ5','Audi e-tron','#e64d00','libre','images_bd/audi_e-tron.jpg','Autonomie : 436 kilomètres, 45 CAD/jour', 45, 2);

INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('BTG 452','Audi e-tron SportBack','#e64d00','libre','images_bd/audi_e-tron_sportback.jpg','Autonomie : 450 kilomètres, 60 CAD/jour', 60, 3);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('BH4 4TG','Audi e-tron SportBack','#063970','libre','images_bd/audi_e-tron_sportback.jpg','Autonomie : 450 kilomètres, 60 CAD/jour', 60, 3);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('BF5 RTS','Audi e-tron SportBack','#990000','enLocation','images_bd/audi_e-tron_sportback.jpg','Autonomie : 450 kilomètres, 60 CAD/jour', 60, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('RTL FA3','Audi e-tron SportBack','#004d1a','libre','images_bd/audi_e-tron_sportback.jpg','Autonomie : 450 kilomètres, 60 CAD/jour', 60, 4);

INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('RFL 523','Mercedes EQC','#a6a6a6','libre','images_bd/mercedes_eqc.jpg','Autonomie : 410 kilomètres, 75 CAD/jour', 75, 4);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('568 5GB','Mercedes EQC','#a6a6a6','enLocation','images_bd/mercedes_eqc.jpg','Autonomie : 410 kilomètres, 75 CAD/jour', 75, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('BT7 RGB','Mercedes EQC','#a6a6a6','enLocation','images_bd/mercedes_eqc.jpg','Autonomie : 410 kilomètres, 75 CAD/jour', 75, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('RQ4 TFQ','Mercedes EQC','#a6a6a6','enLocation','images_bd/mercedes_eqc.jpg','Autonomie : 410 kilomètres, 75 CAD/jour', 75, null);

INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('TRQ PD5','Porshe Taycan','#f2f2f2','libre','images_bd/porsche_taycan.jpg','Autonomie : 450 kilomètres, 90 CAD/jour', 90, 1);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('FTG 3GB','Porshe Taycan','#f2f2f2','libre','images_bd/porsche_taycan.jpg','Autonomie : 450 kilomètres, 90 CAD/jour', 90, 2);

INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('352 256','Tesla Model 3','#e64d00','enLocation','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('568 956','Tesla Model 3','#a6a6a6','enLocation','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('123 569','Tesla Model 3','#a6a6a6','libre','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, 1);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('475 685','Tesla Model 3','#e64d00','enLocation','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('125 253','Tesla Model 3','#f2f2f2','enLocation','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('123 425','Tesla Model 3','#f2f2f2','libre','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, 2);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('154 253','Tesla Model 3','#990000','enLocation','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('123 256','Tesla Model 3','#990000','enLocation','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('GHB 523','Tesla Model 3','#0d0d0d','enLocation','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('142 253','Tesla Model 3','#0d0d0d','enLocation','images_bd/tesla_model_3.jpg','Autonomie : 560 kilomètres, 20 CAD/jour', 20, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('253 695','Tesla Model 3','#0000b3','libre','images_bd/tesla_model_s.jpg','Autonomie : 610 kilomètres, 50 CAD/jour', 20, 4);

INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('256 985','Tesla Model S','#0000b3','enLocation','images_bd/tesla_model_s.jpg','Autonomie : 610 kilomètres, 50 CAD/jour', 20, null);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('156 253','Tesla Model S','#0000b3','enLocation','images_bd/tesla_model_s.jpg','Autonomie : 610 kilomètres, 50 CAD/jour', 20, null);

INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('254 321','Tesla Model X','#f2f2f2','libre','images_bd/tesla_model_x.jpg','Autonomie : 507 kilomètres, 35 CAD/jour', 20, 1);
INSERT INTO `voiture`(`PLAQUE_IMMATRICULATION`, `MODELE`, `COULEUR`, `ETAT`, `URL_IMAGE`, `DESCRIPTION_VOITURE`, `PRIX_PAR_JOUR`, `CENTRE_POSITION`) VALUES ('BHG 25G','Tesla Model X','#f2f2f2','enLocation','images_bd/tesla_model_x.jpg','Autonomie : 507 kilomètres, 35 CAD/jour', 20, null);

