CREATE DATABASE IF NOT EXISTS carbay_db;
USE carbay_db;

DROP TABLE IF EXISTS LOCATION_VOITURE;
DROP TABLE IF EXISTS VOITURE;
DROP TABLE IF EXISTS CENTRE;
DROP TABLE IF EXISTS CLIENT;

create table CENTRE(
ID_CENTRE int PRIMARY KEY,
NOM varchar(50) NOT NULL,
ADRESSE varchar(255) NOT NULL,
LAT varchar(50) NOT NULL,
LNG varchar(50) NOT NULL);

create table VOITURE(
ID_VOITURE int AUTO_INCREMENT PRIMARY KEY,
PLAQUE_IMMATRICULATION varchar(20) UNIQUE,
MODELE varchar(50) NOT NULL,
COULEUR varchar(20) NOT NULL,
ETAT varchar(20) NOT NULL,
URL_IMAGE varchar(50) NOT NULL,
DESCRIPTION_VOITURE varchar(100) NOT NULL,
PRIX_PAR_JOUR int NOT NULL,
CENTRE_POSITION int,
FOREIGN KEY (CENTRE_POSITION) REFERENCES CENTRE(ID_CENTRE));

create table CLIENT(
ID_CLIENT int AUTO_INCREMENT PRIMARY KEY,
NOM varchar(50) NOT NULL,
PRENOM varchar(50) NOT NULL,  
EMAIL varchar(50),
TELEPHONE varchar(20),
NUMERO_CB int,
MOT_DE_PASSE varchar(50));

create table LOCATION_VOITURE(
ID_LOCATION int AUTO_INCREMENT PRIMARY KEY,
PRIX int NOT NULL,
DATE_DEPART date NOT NULL,
DATE_ARRIVEE date NOT NULL,
ID_CLIENT int NOT NULL,
ID_VOITURE int NOT NULL,
CENTRE_DEPART int NOT NULL,
CENTRE_ARRIVEE int NOT NULL,
FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
FOREIGN KEY (ID_VOITURE) REFERENCES VOITURE(ID_VOITURE),
FOREIGN KEY (CENTRE_DEPART) REFERENCES CENTRE(ID_CENTRE),
FOREIGN KEY (CENTRE_ARRIVEE) REFERENCES CENTRE(ID_CENTRE));
